Repository openshift/origin-ci-tool, pull requests merged in 2018-05, with the labels that each got.

#161 Remove nightly dependency repo from origin mirror
  oct/ansible/oct/roles/dependencies/tasks/register_repositories.yml
Labels: size/XS

#163 Add OSE image stages
  oct/cli/package/common_options.py
  oct/cli/provision/remote/all_in_one.py
Labels: size/S

#164 Re-add OCP 3.6-3.12 repos but leave them disabled
  oct/ansible/oct/roles/dependencies/tasks/register_repositories.yml
Labels: size/M

#166 Change image_ready to image_unready
  oct/cli/image_not_ready.py
  oct/oct.py
Labels: lgtm, size/M

#168 Add ansible-service-broker support
  oct/ansible/oct/roles/repositories/tasks/main.yml
  oct/cli/util/repository_options.py
Labels: size/XS
