Repository openshift/origin-ci-tool, pull requests merged in 2019-09, with the labels that each got.

#180 install ansible for RHEL 8
  oct/ansible/oct/playbooks/bootstrap/ansible.yml
  oct/ansible/oct/playbooks/bootstrap/host.yml
  oct/ansible/oct/playbooks/bootstrap/self.yml
Labels: size/M

#181 Fix RHEL 8 check
  oct/ansible/oct/playbooks/bootstrap/ansible.yml
Labels: size/XS

#182 revert back to ansible_distribution
  oct/ansible/oct/playbooks/bootstrap/ansible.yml
Labels: size/XS

#183 gather facts to figure out host info
  oct/ansible/oct/playbooks/bootstrap/host.yml
  oct/ansible/oct/playbooks/bootstrap/self.yml
Labels: size/XS

#184 also gather facts for host
  oct/ansible/oct/playbooks/bootstrap/host.yml
Labels: size/XS

#185 add symlnk for python
  oct/ansible/oct/playbooks/bootstrap/ansible.yml
Labels: size/XS

#186 (hopefully final) update for rhel 8 oct
  oct/ansible/oct/callback_plugins/pretty_progress.py
  oct/ansible/oct/playbooks/bootstrap/ansible.yml
  oct/ansible/oct/playbooks/bootstrap/self.yml
  oct/cli/image_not_ready.py
  oct/config/vagrant.py
Labels: size/M

#187 avoid package for rhel8 nodes
  oct/ansible/oct/playbooks/bootstrap/ansible.yml
  oct/ansible/oct/playbooks/bootstrap/node.yml
  oct/ansible/oct/playbooks/provision/aws-docker-storage.yml
  oct/ansible/oct/playbooks/provision/lvm2.yml
  oct/ansible/oct/playbooks/provision/vagrant-docker-storage.yml
Labels: size/M

#190 Force pip<19.0, Click<7.0 to fix travis tests, pep8<=1.7.0 for noise
  .travis.yml
  oct/ansible/oct/callback_plugins/pretty_progress.py
  oct/config/vagrant.py
  setup.py
Labels: size/S
