Repository openshift/origin-ci-tool, pull requests merged in 2019-10, with the labels that each got.

#188 replace references to `libra` key with new `openshift-dev` key
  oct/ansible/openshift-ansible/README_AWS.md
  oct/ansible/openshift-ansible/playbooks/aws/openshift-cluster/vars.yml
Labels: lgtm, size/XS

#191 allow for f30 to use python3 rules
  oct/ansible/oct/playbooks/bootstrap/ansible.yml
  oct/ansible/oct/playbooks/bootstrap/python3.yml
  oct/ansible/oct/playbooks/bootstrap/self.yml
Labels: size/S

#192 add fedora 30 support in downloading lvm2
  oct/ansible/oct/playbooks/provision/lvm2.yml
  oct/ansible/oct/playbooks/provision/python3.yml
Labels: size/S

#194 two fixes
  oct/ansible/oct/callback_plugins/pretty_progress.py
  oct/ansible/oct/playbooks/bootstrap/ansible.yml
  oct/ansible/oct/playbooks/bootstrap/self.yml
  oct/ansible/oct/playbooks/provision/lvm2.yml
Labels: size/S

#195 use set fact instead of setting variable
  oct/ansible/oct/playbooks/bootstrap/ansible.yml
  oct/ansible/oct/playbooks/bootstrap/python3.yml
  oct/ansible/oct/playbooks/bootstrap/self.yml
  oct/ansible/oct/playbooks/provision/lvm2.yml
  oct/ansible/oct/playbooks/provision/python3.yml
Labels: size/M

#196 AMI build fixes for key rotation and build speed
  oct/ansible/oct/playbooks/prepare/user.yml
  oct/ansible/oct/playbooks/provision/aws-docker-storage.yml
Labels: lgtm, size/S
